
WEEKDAY_POINT = 1
WEEKEND_POINT = 2
TRAINED_POINT = 3
BONUS_ATTENDANCE = 10
BONUS_POINT = 10

DAY_IDX_DICT = {
    "monday":0,
    "tuesday":1,
    "wednesday":2,
    "thursday":3,
    "friday":4,
    "saturday":5,
    "sunday":6
}

GOLD_MINIMUM = 50
SILVER_MINIMUM = 30
GOLD_GRADE = 1
SILVER_GRADE = 2
NORMAL_GRADE = 0
WEEKEND_IDX = [5, 6]
TRAINED_DAY_IDX = 2

GOLD_GRADE = 1
SILVER_GRADE = 2
NORMAL_GRADE = 0
